name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        # Install dev tools (pytest, httpx, pytest-asyncio, pytest-cov)
        pip install pytest pytest-asyncio httpx pytest-cov

    - name: Prepare environment
      run: |
        # Copy example env file so Pydantic loads required variables
        cp .env.example .env
        # Ensure project root is in Python path
        export PYTHONPATH=$PYTHONPATH:$(pwd)

    - name: Run tests with coverage
      run: |
        pytest --maxfail=1 --disable-warnings -q --cov=. --cov-report=term-missing
